# Build and publish the Docker image with the latest tag
name: Build and Publish Image

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Determine image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/globalgoalsdirectory/translator
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.gpu
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # We only read the cache but we do not write. That is because caches
          # between different tags are not shared. So they only end up taking
          # up space with no benefit for build speed.
          cache-from: type=gha
