# Run on every push to main. This keeps the GHA cache on the main branch up to
# date and allows builds on other branches to read from the cache.
name: Build Image (Staging)

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "{context}/Dockerfile.gpu"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
